### PR TITLE
Enable bitcode + chroma threshold

### PR DESCRIPTION
**Pull request by ramicaza**
This is the corresponding PR for [this.](https://github.com/ViroCommunity/virocore/pull/63) Please see that PR to learn of the changes in this one.

Note: had to remove target 'ViroReact_release_tests' from the Podfile, not sure what that was about...

### CODE REVIEW

**Review by NS-BOBBY-C — COMMENTED** [review]
I've noticed that there are some binary files being included in this PR. Is this necessary?

**Review by NS-BOBBY-C — COMMENTED** [review]
Also what are the hourglass files for? I assume they are a model which snuck their way in - or some sort of loading model.

**Review by NS-BOBBY-C — COMMENTED** [review]
Is there sound issues being fixed in this PR as well?

I have some hesitations about including ios/dist unless we need to. Why are these being included?

**Review by doranteseduardo — APPROVED** [review]
Everything looks good, my only concern is the binaries size increasing around 250%, but I think is not a big deal.

**Comment by doranteseduardo** [comment]
> Is there sound issues being fixed in this PR as well?
> 
> I have some hesitations about including ios/dist unless we need to. Why are these being included?

As bitcode is now enabled, the ViroCore has to be rebuild.

**Pull request merged**
