### PR TITLE
Fix for 'Tried to register two views with the same name VRTQuad' in ViroSurface

### PR DESCRIPTION
**Pull request by ls30378**
Fix for error "Tried to register two views with the same name VRTQuad"

### CODE REVIEW

**Review by sumittops — APPROVED** [review]

**Comment by sumittops** [comment]
@ls30378 I've faced this same issue when I installed the latest release yesterday. Upon investigation, I concluded  the same changes would be needed.

Thus, approved!

**Review by ElyasAsmad — APPROVED** [review]

**Review by saadqbal — APPROVED** [review]

**Review by luizcorreia — APPROVED** [review]
Looks good to me

**Review by SumanBhowmick — APPROVED** [review]

**Comment by ansarikhurshid786** [comment]
This commit is also fixed my issue. Please approved and update in main branch.

**Comment by donni106** [comment]
relates to #193, right?!

**Review by adelarsq — APPROVED** [review]

**Comment by junomirab0** [comment]
help me release this verison =((((((((((

**Comment by skizzo** [comment]
This error is still happening when testing on a device, even though I applied the patch :( what else could go wrong here? Would be really thankful for some help!

**Pull request merged**
